# Generated by Django 5.2.8 on 2025-11-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_time_of_order',
            new_name='cost',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
    ]
