# Generated by Django 5.2.8 on 2025-12-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_applied_discount_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('preparing', 'preparing'), ('completed', 'completed')], default='accepted', max_length=20),
        ),
    ]
