# Generated by Django 5.2.8 on 2025-11-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='discount_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
