# Generated by Django 5.2.8 on 2025-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountitem',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Процент'), ('GIFT_ITEM', 'Товар в подарок')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='every_n_item_free',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='is_first_order_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='min_item_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
