# Generated by Django 5.2.8 on 2025-11-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='cost',
        ),
    ]
