# Generated by Django 5.2.8 on 2025-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_price_menuitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
